spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internet_facing_plus?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080

logging:
  config: 'classpath:logback-boot.xml'

myconfig:
  cors-address: http://localhost:8000
  data-root-path: F:\warehouse\SePractice\testdir
